import { useEffect, useState } from 'react'

const people = [{ x: 27, y: 31, delay: '0ms' }, { x: 39, y: 21, delay: '280ms' }, { x: 51, y: 34, delay: '520ms' }, { x: 64, y: 24, delay: '760ms' }, { x: 73, y: 40, delay: '110ms' }, { x: 34, y: 52, delay: '640ms' }, { x: 57, y: 55, delay: '380ms' }, { x: 68, y: 62, delay: '900ms' }]

export default function MovementField({ inflow, outflow, event }) {
  const [active, setActive] = useState(null)
  useEffect(() => { if (!event) return; setActive(event.timestamp); const timer = setTimeout(() => setActive(null), 1450); return () => clearTimeout(timer) }, [event])
  return <section className="movement-section" aria-labelledby="movement-title"><div className="section-rule-heading"><p className="eyebrow" id="movement-title">Live movement</p><h2>People moving through the monitored space</h2></div><div className="movement-layout"><div className="flow-counter flow-in"><span>IN</span><strong>{inflow ?? '—'}</strong><small>latest interval</small></div><div className="movement-diagram" aria-label="Animated movement diagram showing people entering and leaving the monitored space"><span className="direction direction-in">IN <b>↓</b></span><div className="flow-lines" aria-hidden="true"><i /><i /><i /><i /></div>{people.map((person, index) => <span key={index} className="person-mark" style={{ left: `${person.x}%`, top: `${person.y}%`, animationDelay: person.delay }} aria-hidden="true" />)}{active && <span className="event-marker event-in" key={`in-${active}`} aria-hidden="true" />}{active && <span className="event-marker event-out" key={`out-${active}`} aria-hidden="true" />}<div className="monitored-space"><span>MONITORED</span><strong>SPACE</strong><small>occupancy</small></div><span className="direction direction-out">OUT <b>↓</b></span></div><div className="flow-counter flow-out"><span>OUT</span><strong>{outflow ?? '—'}</strong><small>latest interval</small></div></div><p className="movement-note">Markers appear only when a new telemetry timestamp reports movement.</p></section>
}
